### ISSUE TITLE
Settings used to generate these images?

### ISSUE THREAD

**Issue by Goldenkoron** [djbielejeski/Stable-Diffusion-Regularization-Images-woman_ddim#1]
Hi, I have been trying to make good regularization images for days but none of my models trained with them come out nearly as good as when I use yours. I assumed it was DDIM 50 steps but the quality still isn't there... is there a specific CFG setting maybe?

**Comment by djbielejeski** [comment]
I used the following settings

ddim @ 50 steps, CFG 10.0, prompt: "woman", size: 512x512, no upscaling, no
face retouching
